danai.lo: /home/ivan/ivmos_github/danai/danai.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ivan/ivmos_github/danai $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ivan/ivmos_github/danai/danai.c -o danai.lo 
$(phplibdir)/danai.la: ./danai.la
	$(LIBTOOL) --mode=install cp ./danai.la $(phplibdir)

./danai.la: $(shared_objects_danai) $(DANAI_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_danai) $(DANAI_SHARED_LIBADD)

